<?php
/**
 * FastRide PDF Generator
 * 
 * This script captures the output of any existing PHP page and converts it to a PDF 
 * using the Dompdf library.
 */

// 1. LOAD DOMPDF
// Note: You must run 'composer require dompdf/dompdf' in your terminal first.
$autoloadPath = __DIR__ . '/vendor/autoload.php';
if (!file_exists($autoloadPath)) {
    die("<h3>Error: Dompdf not found.</h3>
         <p>Please install it by running this command in your project root:</p>
         <code>composer require dompdf/dompdf</code>");
}
require_once $autoloadPath;

use Dompdf\Dompdf;
use Dompdf\Options;

// 2. CONFIGURE OPTIONS
$options = new Options();
$options->set('isRemoteEnabled', true);      // Allows loading CSS/images from your server URL
$options->set('isHtml5ParserEnabled', true); // Better support for modern HTML
$options->set('defaultFont', 'Arial');

$dompdf = new Dompdf($options);

// 3. CAPTURE PAGE CONTENT
// Identify which page to convert
$targetPage = isset($_GET['page']) ? $_GET['page'] : 'index.php';

// If a rentalId is provided, we default to the invoice page
if (isset($_GET['rentalId'])) {
    $targetPage = 'invoice.php';
}

// Security: Prevent accessing files outside current directory or non-php files
$safePage = basename($targetPage);
if (!file_exists(__DIR__ . '/' . $safePage) || pathinfo($safePage, PATHINFO_EXTENSION) !== 'php') {
    die("Error: Invalid page requested.");
}

// Define a constant so pages can detect if they are being rendered for PDF
if (!defined('IS_GENERATING_PDF')) {
    define('IS_GENERATING_PDF', true);
}

// Use Output Buffering to capture the HTML generated by the PHP script
ob_start();
try {
    // Include the page. This executes all PHP/Database logic.
    // $_GET parameters are shared with the included file automatically.
    include __DIR__ . '/' . $safePage;
} catch (Exception $e) {
    ob_end_clean();
    die("Error capturing page: " . $e->getMessage());
}
$html = ob_get_clean();

// 4. PREPARE HTML FOR PDF
// A. Build Base URL for assets (Images/CSS)
$protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? "https" : "http";
$baseUrl = $protocol . "://" . $_SERVER['HTTP_HOST'] . rtrim(dirname($_SERVER['PHP_SELF']), '/\\') . "/";

// B. Inject <base> tag into <head> so absolute paths work for images/CSS
if (strpos($html, '<head>') !== false) {
    $html = str_replace('<head>', '<head><base href="' . $baseUrl . '">', $html);
} else {
    $html = '<base href="' . $baseUrl . '">' . $html;
}

// C. Inject PDF-specific styles to fix Bootstrap layouts and hide UI elements
$pdfSpecificStyles = "
<style>
    /* 1. Hide interactive elements not needed in PDF */
    .navbar, footer, .btn, .pdf-download-btn, .no-pdf, #compareToolbar, .modal { 
        display: none !important; 
    }

    /* 2. Reset Layout Fixes */
    body { padding-top: 0 !important; margin: 0; font-size: 11pt; background: white !important; color: black !important; }
    
    /* Only apply Bootstrap fixes if we are NOT on a clean invoice page */
    " . ($safePage !== 'invoice.php' ? "
    .container { width: 100% !important; max-width: 100% !important; padding: 0 !important; margin: 0 !important; }
    .hero-section { min-height: auto !important; padding: 40px 20px !important; background: #0f172a !important; color: white !important; }
    .row { display: block; width: 100%; margin: 0; }
    .col-md-4, .col-md-6, .col-lg-4 { display: inline-block; vertical-align: top; padding: 10px; box-sizing: border-box; }
    .col-md-4, .col-lg-4 { width: 32%; }
    .col-md-6 { width: 49%; }
    " : "") . "

    /* 3. Handle Colors */
    * { -webkit-print-color-adjust: exact !important; print-color-adjust: exact !important; }
    img { max-width: 300px; height: auto; }
</style>
";

if (strpos($html, '</head>') !== false) {
    $html = str_replace('</head>', $pdfSpecificStyles . '</head>', $html);
}

// 5. LOAD, RENDER, AND STREAM
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();

// 6. Output to browser
$prefix = ($safePage === 'invoice.php') ? "invoice_" . ($_GET['rentalId'] ?? "") : str_replace('.php', '', $safePage);
$filename = $prefix . "_" . date('Y-m-d') . ".pdf";
$dompdf->stream($filename, ["Attachment" => 1]);
exit;
